spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
#spring.datasource.url=jdbc:postgresql://localhost:5432/student_service?createDatabaseIfNotExist=true
spring.datasource.url=${DEV_DB_URL}
#spring.datasource.username=devuser
spring.datasource.username=${DEV_USERNAME}
#spring.datasource.password=devuser
spring.datasource.password=${DEV_PASSWORD}
server.port= 8085
spring.jpa.properties.hibernate.default_schema=studentschema
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Specify the path of the OpenAPI documentation
springdoc.api-docs.path=/api-docs

# Specify the path of the Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Enable or disable Swagger UI
springdoc.swagger-ui.enabled=true
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000
token.signing.key=413F4428472B4B6250655368566D5970337336763979244226452948404D6351